### ISSUE TITLE
BUG: Transformers backend. Openvino not working

### ISSUE THREAD

**Issue by fakezeta** [mudler/LocalAI#3223]
**LocalAI version:**
2.19.4

**Environment, CPU architecture, OS, and Version:**
docker

**Describe the bug**
optimum-intel 1.18.2 does not work with pytorch version <2.4.0 

```
Error: module 'torch' has no attribute 'uint16'
```

An upstream PR is already merged: https://github.com/huggingface/optimum-intel/pull/863
I add this as a warning to the user community and suggest waiting for the upcoming release that hopefully should be out soon©️ 

Switching to pytorch 2.4 breaks Intel Extension for Pytorch (so Intel GPU acceleration for transformers) since it's working maximum with pytorch 2.3 

To be closed after the new Optimum-Intel version is out.

**Comment by fakezeta** [comment]
Issue can be closed as new version of Optimum-Intel has been released and integrated in the latest docker images
