### PR TITLE
fix: pin version of setuptools for intel builds to work around #2406

### LINKED ISSUE #2406: [BUG] setuptools 70.0.0 breaks PyTorch 2.1
**LocalAI version:**
2.16

**Environment, CPU architecture, OS, and Version:**
docker

**Describe the bug**
As described in [#4376](https://github.com/pypa/setuptools/issues/4376#issuecomment-2126162839) PyTorch <2.2 is not working with setuptools 70.0.0
This impact most of python backend. 

**Logs**
```
Error: cannot import name 'packaging' from 'pkg_resources' (/build/backend/python/transformers/venv/lib/python3.10/site-packages/pkg_resources/__init__.py)
```
**Additional context**
Bumping Pytorch for all the builds is not possible due to Intel still not releasing PyTorch 2.2+ package. We should fix the version to `setuptools==69.5.1` until we can safely bump PyTorch to 2.2+

### PR DESCRIPTION
**Pull request by cryptk**
**Description**

This PR fixes #2406

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by mudler — APPROVED** [review]
:100: Thanks!
