### ISSUE TITLE
[BUG] setuptools 70.0.0 breaks PyTorch 2.1

### ISSUE THREAD

**Issue by fakezeta** [mudler/LocalAI#2406]
**LocalAI version:**
2.16

**Environment, CPU architecture, OS, and Version:**
docker

**Describe the bug**
As described in [#4376](https://github.com/pypa/setuptools/issues/4376#issuecomment-2126162839) PyTorch <2.2 is not working with setuptools 70.0.0
This impact most of python backend. 

**Logs**
```
Error: cannot import name 'packaging' from 'pkg_resources' (/build/backend/python/transformers/venv/lib/python3.10/site-packages/pkg_resources/__init__.py)
```
**Additional context**
Bumping Pytorch for all the builds is not possible due to Intel still not releasing PyTorch 2.2+ package. We should fix the version to `setuptools==69.5.1` until we can safely bump PyTorch to 2.2+
